remote_theme: pages-themes/hacker@v0.2.0

# Setup
title:               'How I Built This: Digital Methods for 18th-Century Studies'
tagline:             
description:         'A panel at ASECS 2023'
url:                 'http://atmcgrath.github.io'
baseurl:             '/asecs-built-dh/'