remote_theme: pages-themes/slate@v0.2.0

# Setup
title:               How I Built This
tagline:             Digital Methods for 18th-Century Studies
description:         'A panel at ASECS 2023'
url:                 'http://atmcgrath.github.io'
baseurl:             '/asecs-23'